# Stage 1: Build the application
FROM node:18-slim as builder
RUN mkdir /app
WORKDIR /app

# Copy files
COPY ["package.json", "yarn.lock", "preinstall.js", "./"]
COPY extensions /app/extensions
COPY modes /app/modes
COPY platform /app/platform

# Run the install before copying the rest of the files
RUN yarn config set workspaces-experimental true
RUN yarn install --frozen-lockfile --verbose

COPY . .

RUN yarn run build:orthanc

# Stage 2: Bundle the built application into a Docker container
FROM node:18-alpine

# Copy dist folder, server.js and node_modules from build stage
COPY --from=builder /app/platform/viewer/dist /app/dist
COPY --from=builder /app/platform/viewer/server.js /app/server.js
COPY --from=builder /app/node_modules /app/node_modules

# Start Node services
CMD node /app/server.js
