FROM node:18-alpine
WORKDIR /app

# Copy dist folder, server.js and node_modules from build stage
COPY ./platform/viewer/dist /app/dist
COPY ./platform/viewer/server.js /app/server.js
COPY ./node_modules /app/node_modules

EXPOSE 80

# Start Node services
CMD node /app/server.js
